"""empty message

Revision ID: f4a2f938a8ec
Revises: 7a7648d92d99
Create Date: 2021-06-19 21:33:44.566412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a2f938a8ec'
down_revision = '7a7648d92d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.add_column('comments', sa.Column('comment', sa.Text(), nullable=False))
    op.alter_column('comments', 'pitch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'], ondelete='SET NULL')
    op.drop_column('comments', 'description')
    op.drop_constraint('downvotes_pitch_id_fkey', 'downvotes', type_='foreignkey')
    op.drop_constraint('downvotes_user_id_fkey', 'downvotes', type_='foreignkey')
    op.create_foreign_key(None, 'downvotes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'downvotes', 'pitches', ['pitch_id'], ['id'], ondelete='SET NULL')
    op.add_column('pitches', sa.Column('pitch', sa.String(), nullable=False))
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_pitches_description', table_name='pitches')
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    op.drop_constraint('pitches_owner_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('pitches', 'owner_id')
    op.drop_column('pitches', 'description')
    op.drop_constraint('upvotes_user_id_fkey', 'upvotes', type_='foreignkey')
    op.drop_constraint('upvotes_pitch_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'upvotes', 'pitches', ['pitch_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'pass_secure')
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_pitch_id_fkey', 'upvotes', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key('upvotes_user_id_fkey', 'upvotes', 'users', ['user_id'], ['id'])
    op.add_column('pitches', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_owner_id_fkey', 'pitches', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.create_index('ix_pitches_description', 'pitches', ['description'], unique=False)
    op.alter_column('pitches', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'time')
    op.drop_column('pitches', 'pitch')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.create_foreign_key('downvotes_user_id_fkey', 'downvotes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('downvotes_pitch_id_fkey', 'downvotes', 'pitches', ['pitch_id'], ['id'])
    op.add_column('comments', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'pitches', ['pitch_id'], ['id'])
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'pitch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'comment')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
